<a href="https://colab.research.google.com/github/bogluc/PyTorch/blob/main/Py_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [153]:
import torch

l = [1, 2, 3, 4]
print(l)

v1 = torch.arange(12)
print(v1.shape, v1.numel())
print(v1)

v3 = torch.tensor([[1, 2, 3, 4]])
print(v3.shape, v3.numel())
v1 = v1.reshape(1,-1)
print(v1.shape, v1.numel())
print(v1)
v4 = torch.zeros(2, 3, 4)
print(v4.shape, v4.numel())
print(v4)
torch.manual_seed(7)
v5 = torch.randn(3,4)
print(v5.shape, v5.numel())
print(v5)

v2 = torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(v2)
print("v2: size = ", v2.shape, ", no. el = ", v2.numel())
v2[-2:,-2:]




[1, 2, 3, 4]
torch.Size([12]) 12
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([1, 4]) 4
torch.Size([1, 12]) 12
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])
torch.Size([2, 3, 4]) 24
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([3, 4]) 12
tensor([[-0.1468,  0.7861,  0.9468, -1.1143],
        [ 1.6908, -0.8948, -0.3556,  1.2324],
        [ 0.1382, -1.6822,  0.3177,  0.1328]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
v2: size =  torch.Size([3, 3]) , no. el =  9


tensor([[5, 6],
        [8, 9]])