<a href="https://colab.research.google.com/github/bogluc/PyTorch/blob/main/Py_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [158]:
import torch

l = [1, 2, 3, 4]
print(l)

v1 = torch.arange(12)
print(v1.shape, v1.numel())
print(v1)

v3 = torch.tensor([[1, 2, 3, 4]])
print(v3.shape, v3.numel())
v1 = v1.reshape(1,-1)
print(v1.shape, v1.numel())
print(v1)
v4 = torch.zeros(2, 3, 4)
print(v4.shape, v4.numel())
print(v4)
torch.manual_seed(7)
v5 = torch.randn(3,4)
print(v5.shape, v5.numel())
print(v5)

v2 = torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(v2)
print("v2: size = ", v2.shape, ", no. el = ", v2.numel())
v2[-2:,-2:]
e = torch.exp(v4)
e




[1, 2, 3, 4]
torch.Size([12]) 12
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([1, 4]) 4
torch.Size([1, 12]) 12
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])
torch.Size([2, 3, 4]) 24
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([3, 4]) 12
tensor([[-0.1468,  0.7861,  0.9468, -1.1143],
        [ 1.6908, -0.8948, -0.3556,  1.2324],
        [ 0.1382, -1.6822,  0.3177,  0.1328]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
v2: size =  torch.Size([3, 3]) , no. el =  9


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [71]:
import torch

X = torch.rand(3,4)
Y = torch.rand(3,4)

before = id(Y)
print(before)

Y[:] = X+Y
X-Y

print(id(Y))
before == id(Y)

Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z = X + Y
print('id(Z):', id(Z))

before = id(X)
print("id(X)", id(X))
X += Y
print("id(X)", id(X))
id(X) == before

a = torch.tensor([3.5])
a, float(a), int(a),a.item()

A = X.numpy()
B = torch.from_numpy(A)
print(X > Y)
type(X), type(A), type(B)


#torch.cat((X,Y), dim=-2)
#X.sum()

#Y1 = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
#Y1.shape

139256194911840
139256194911840
id(Z): 139256196683392
id(Z): 139256206325184
id(X) 139256546914976
id(X) 139256546914976
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


(torch.Tensor, numpy.ndarray, torch.Tensor)

In [4]:
import pandas as pd
import os

from google.colab import drive
drive.mount('/content/drive')

folder_path = '/content/drive/My Drive/Colab Notebooks/Data'
print(f"Listing files in: {folder_path}")

if os.path.exists(folder_path):
    files_in_folder = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
    if files_in_folder:
        print("Available CSV files:")
        for i, file_name in enumerate(files_in_folder):
            print(f"{i+1}. {file_name}")
    else:
        print("No CSV files found in this folder.")
else:
    print(f"The folder {folder_path} does not exist. Please check the path.")

# User input for selecting the file
selected_file_name = input("Enter the name of the CSV file you want to open (e.g., Houses1.csv): ")

file_path = os.path.join('/content/drive/My Drive/Colab Notebooks/Data', selected_file_name)

if os.path.exists(file_path):
    df_selected = pd.read_csv(file_path)
    print(f"\nDataFrame '{selected_file_name}' loaded successfully. Displaying all entries:")
    print(df_selected)
else:
    print(f"Error: The file '{selected_file_name}' was not found at '{file_path}'. Please check the file name and path.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Listing files in: /content/drive/My Drive/Colab Notebooks/Data
Available CSV files:
1. Houses1.csv
2. Houses2.csv
Enter the name of the CSV file you want to open (e.g., Houses1.csv): Houses2.csv

DataFrame 'Houses2.csv' loaded successfully. Displaying all entries:
   No. Rooms   Roof  Surface   Price
0          2    NaN      100  100000
1          3  Slant      120  120000
2          4    NaN      140  140000
3          5     R1      150  150000
4          6     R2      160  160000
5          7     R3      170  170000


In [87]:
import os
import pandas as pd
import torch

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')

with open(data_file, 'w') as f:
  f.write('''NumRooms,RoofType,Price
          ,NA,
          2,NA,11
          4,Slate,22
          ,PIG,66
          77,''')

data = pd.read_csv(data_file, skipinitialspace=True)

print('data type is ', type(data))
print(data)

#df = pd.DataFrame(data)

inputs = data.iloc[:, 0:2]
print('>>>1: inputs type is ', type(inputs))
targets = data.iloc[:, 2]

print('>>> Before get_dummies')
print(inputs)

inputs = pd.get_dummies(inputs, dummy_na=True, dtype=int)

print('>>> After get_dummies')
print('>>>', inputs)
#print('>>>>2: inputs type is ', type(inputs))

inputs = inputs.fillna(inputs.mean())
print('>>> After fillna ')
print(inputs)
targets = targets.fillna(targets.mean())

X = torch.tensor(inputs.to_numpy())
Y = torch.tensor(targets.to_numpy(), dtype = int)

print(X)
print(Y)

#print(df)

#days = pd.Series(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Monday'])
#print(pd.get_dummies(days, dtype='int'))

#inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
#inputs = pd.get_dummies(inputs, dummy_na=True)
#print(inputs)

data type is  <class 'pandas.core.frame.DataFrame'>
   NumRooms RoofType  Price
0       NaN      NaN    NaN
1       2.0      NaN   11.0
2       4.0    Slate   22.0
3       NaN      PIG   66.0
4      77.0      NaN    NaN
>>>1: inputs type is  <class 'pandas.core.frame.DataFrame'>
>>> Before get_dummies
   NumRooms RoofType
0       NaN      NaN
1       2.0      NaN
2       4.0    Slate
3       NaN      PIG
4      77.0      NaN
>>> After get_dummies
>>>    NumRooms  RoofType_PIG  RoofType_Slate  RoofType_nan
0       NaN             0               0             1
1       2.0             0               0             1
2       4.0             0               1             0
3       NaN             1               0             0
4      77.0             0               0             1
>>> After fillna 
    NumRooms  RoofType_PIG  RoofType_Slate  RoofType_nan
0  27.666667             0               0             1
1   2.000000             0               0             1
2   4.000000        

In [28]:
import torch

x = torch.tensor(3)
y = torch.tensor(2)
x+y, x-y, x*y, x**y

X = torch.arange(3)
X, len(X), X.shape, X[len(X)-1], X[-len(X)], X[:]

(tensor([0, 1, 2]),
 3,
 torch.Size([3]),
 tensor(2),
 tensor(0),
 tensor([0, 1, 2]))